class DesignComponent extends DCLogic {
  F = ['#23343f','#4a3b31','#33413a','#3d3447','#5a4a30','#27403f','#4a2f33','#30384a','#41392c','#2d3b2d'];
  TPL = [['Hook · Story · Offer','TikTok','0:30','9:16'],['Product Spotlight','Product Ads','0:20','9:16'],['Listing Walkthrough','Real Estate','1:00','16:9'],['Feature Launch','SaaS Ads','0:45','16:9'],['Top 5 Countdown','Faceless Content','0:58','9:16'],['Mini Lesson','Education','1:30','16:9'],['UGC Testimonial','Instagram Reels','0:25','9:16'],['Explainer in 3 Acts','Explainer','1:15','16:9'],['Flash Sale','Ecommerce','0:15','1:1'],['Channel Intro','YouTube','0:40','16:9'],['Quick Tip','YouTube Shorts','0:30','9:16'],['Before / After','Ecommerce','0:20','4:5']];
  state = { w: typeof window!=='undefined'?window.innerWidth:1400, page:(typeof localStorage!=='undefined'&&localStorage.getItem('rs_site_page'))||this.props.startPage||'home', menu:false, faq:0, yearly:false, calcN:200, calcMode:'Free providers', tq:'', tcat:'All', tpl:0, doc:'install', sending:false, sent:false, logging:false, loginErr:false, rpw:'Reelsmith!26', rpw2:'Reelsmith!26', forgotSent:false, cookie:'x', legal:'terms', coPlan:2, coMethod:'Card', paying:false, declined:false, paid:false, resetDone:false, ob:0, obUses:['Product ads'] };
  componentDidMount(){ this.onR=()=>this.setState({w:window.innerWidth}); window.addEventListener('resize',this.onR); let c=null; try{c=localStorage.getItem('rs_cookie')}catch(e){} this.setState({cookie:c}); }
  componentDidUpdate(pp){ if(pp.startPage!==this.props.startPage&&this.props.startPage) this.go(this.props.startPage); }
  componentWillUnmount(){ window.removeEventListener('resize',this.onR); }
  go=p=>{ this.setState({page:p,menu:false}); try{localStorage.setItem('rs_site_page',p)}catch(e){} window.scrollTo(0,0); };
  chips(list,cur,fn){ return list.map(l=>{const a=l===cur; return {label:l,on:()=>fn(l),segBg:a?'#fff':'transparent',segSh:a?'0 1px 2px rgba(0,0,0,.08)':'none',bg:a?'#17181a':'#fff',fg:a?'#fff':'#3a3c40',bd:a?'#17181a':'#e1e0dc'};}); }
  tdim(r,scale){ const d={'9:16':[96,170],'16:9':[190,107],'1:1':[140,140],'4:5':[124,155]}[r]; return [d[0]*(scale||1)+'px',d[1]*(scale||1)+'px']; }
  renderVals(){
    const s=this.state, W=s.w, isMobile=W<760, narrow=W<1000;
    const g={}; ['home','features','pricing','providers','templates','template','docs','contact','login','register','forgot','verify','reset','twofa','about','legal','changelog','checkout','e404','e500','maintenance','suspended','onboarding'].forEach(k=>g[k]=()=>this.go(k));
    const legalKeys=['terms','privacy','refund','cookies','license'];
    legalKeys.forEach(k=>g[k]=()=>{this.setState({legal:k}); this.go('legal');});
    const isAuth=['login','register','forgot','verify','reset','twofa'].includes(s.page);
    const isSys=['e500','maintenance','suspended'].includes(s.page);
    const bare=isAuth||isSys||s.page==='onboarding';
    const p={home:s.page==='home',features:s.page==='features',pricing:s.page==='pricing',providers:s.page==='providers',templates:s.page==='templates',template:s.page==='template',docs:s.page==='docs',contact:s.page==='contact',auth:isAuth,about:s.page==='about',legal:s.page==='legal',changelog:s.page==='changelog',checkout:s.page==='checkout',e404:s.page==='e404',system:isSys,onboarding:s.page==='onboarding'};
    const LEGAL={
      terms:['Terms of Service','These terms govern your use of the service operated by the installation owner. By creating an account you agree to them.',[['Your account','You must provide accurate information and keep your password secure. You are responsible for activity under your account.'],['Acceptable use','Do not generate content that is illegal, infringes others\' rights, impersonates real people without consent, or violates your AI providers\' policies.'],['Content ownership','You own the videos you create. You grant us a limited licence to store and process them only to provide the service.'],['Credits and billing','Credits are consumed per generation as shown in the app. Unused plan credits expire as described on the pricing page.'],['Termination','We may suspend accounts that breach these terms. You can close your account at any time from Settings.'],['Liability','The service is provided as is. Our liability is limited to the amount you paid in the 12 months before a claim.']]],
      privacy:['Privacy Policy','This policy explains what personal data we collect, why, and the choices you have.',[['Data we collect','Account details, the content you upload or generate, usage and billing records, and basic device information.'],['AI providers','Prompts and assets are sent to the AI providers configured for this installation, only to complete your request. Their own privacy policies apply.'],['How we use data','To run the service, process payments, prevent abuse and, if you opt in, improve the product with aggregated analytics.'],['Retention','Content is kept while your account is active. Deleted projects are removed from storage within 30 days.'],['Your rights','You can access, export or delete your data from Settings, or by contacting support.']]],
      refund:['Refund Policy','We want you to be happy with your plan.',[['Subscriptions','You can cancel anytime. Your plan stays active until the end of the billing period.'],['Refund window','First-time subscriptions can be refunded in full within 14 days if fewer than 100 credits were used.'],['Failed generations','Credits used by a render that failed due to a system error are returned automatically.'],['Credit packs','One-time credit packs are non-refundable once any credits have been used.']]],
      cookies:['Cookie Policy','We use a small number of cookies to run the service.',[['Essential cookies','Keep you signed in, protect forms and remember your cookie choice. These cannot be turned off.'],['Analytics cookies','Optional. Help us understand which features are used. Set only if you choose “Accept all”.'],['Changing your choice','Use the cookie settings link in the footer at any time.']]],
      license:['License Agreement','Terms for purchasers of the self-hosted Reelsmith software.',[['Regular license','One installation on one domain for you or a single client. End users may be charged.'],['Extended license','Required if you sell the software itself as a hosted product to multiple businesses.'],['White-label','You may remove Reelsmith branding and rebrand the application under either license.'],['Updates','Includes 12 months of updates and support. Renew to keep receiving new versions.']]]
    };
    const L=LEGAL[s.legal];
    const coP=[['Starter',19,1500],['Professional',49,5000],['Agency',99,15000]][s.coPlan];
    const coSub=s.yearly?coP[1]*12:coP[1], coDisc=s.yearly?coSub*0.2:0;
    const pwScore=Math.min(4,(s.rpw.length>=8)+(/[A-Z]/.test(s.rpw))+(/[0-9]/.test(s.rpw))+(/[^A-Za-z0-9]/.test(s.rpw)));
    const pwCol=['#e1e0dc','oklch(0.6 0.2 25)','oklch(0.75 0.15 70)','oklch(0.7 0.13 120)','oklch(0.62 0.14 150)'][pwScore];
    const SYS={e500:{icon:'icon-server-crash',ibg:'oklch(0.95 0.035 25)',ifg:'oklch(0.5 0.18 25)',title:'Something went wrong on our end',body:'The server hit an unexpected error. It has been logged, and the admin has been notified. Try again in a moment.',meta:'Error reference · 500 · req_7f2a91c',pLabel:'Try again',primary:()=>this.go('home')},maintenance:{icon:'icon-wrench',ibg:'oklch(0.95 0.05 85)',ifg:'oklch(0.5 0.13 70)',title:'We\'re upgrading',body:'We\'re installing version 2.4.1. Your projects are safe, and renders in progress will resume automatically.',meta:'Back in about 10 minutes · 14:30 UTC',pLabel:'Check again',primary:()=>this.go('home')},suspended:{icon:'icon-ban',ibg:'oklch(0.95 0.035 25)',ifg:'oklch(0.5 0.18 25)',title:'Your account is suspended',body:'Access to john@acme.co has been paused by an administrator. Your projects and credits are kept. Contact support to resolve this.',meta:'',pLabel:'Back to home',primary:()=>this.go('home')}};
    const SY=SYS[s.page]||SYS.e500;
    const useList=[['Product ads','shopping-bag'],['Social shorts','smartphone'],['YouTube videos','square-play'],['Explainers','presentation'],['Real estate','house'],['Education','graduation-cap']];
    const nav=[['Features','features'],['Templates','templates'],['Pricing','pricing'],['AI Providers','providers'],['Docs','docs'],['Contact','contact']].map(n=>({label:n[0],go:g[n[1]],bg:s.page===n[1]?'#ebeae6':'transparent',fg:s.page===n[1]?'#17181a':'#3a3c40'}));
    const mockScenes=[['01','5s','Barely had a sip?','Ever get to 3pm and realize you\'ve barely had a sip?','#2f4b4b','Visual ready'],['02','6s','It reminds you','Hydra glows when it\'s time to drink.','#3d3447','Visual ready'],['03','6s','Tracks every sip','Every sip syncs to your phone.','#30384a','Generating…'],['04','6s','Cold for 24 hours','Ice-cold for 24 hours, wherever you go.','#5a4a30','Visual ready'],['05','7s','Shop at hydra.co','Get yours at hydra.co.','#23343f','Visual ready']].map((m,i)=>({n:m[0],d:m[1],w:parseInt(m[1]),cap:m[2],narr:m[3],c:m[4],st:m[5],sbg:m[5]==='Visual ready'?'oklch(0.95 0.04 150)':'oklch(0.95 0.03 250)',sfg:m[5]==='Visual ready'?'oklch(0.42 0.12 150)':'oklch(0.45 0.13 250)',bg:i===1?'#26282d':'transparent',bd:i===1?'#3a3c42':'transparent'}));
    const plansBase=[['Free',0,'Try it with free AI providers.',['50 credits / month','3 videos / month','720p export','Free AI models']],['Starter',19,'For creators posting weekly.',['1,500 credits / month','30 videos / month','1080p, no watermark','Brand kit']],['Professional',49,'For teams publishing daily.',['5,000 credits / month','Unlimited videos','Custom voices','API access']],['Agency',99,'For agencies serving clients.',['15,000 credits / month','5 team seats','Client workspaces','White-label exports']]];
    const planCard=(pl,i)=>{const pop=i===2, price=s.yearly?Math.round(pl[1]*0.8):pl[1]; return {name:pl[0],price:'$'+price,per:'/ month',desc:pl[2],feats:pl[3],pop,note:pl[1]===0?'Free forever':s.yearly?'billed $'+price*12+' yearly':'billed monthly',bg:pop?'#111214':'#fff',fg:pop?'#fff':'#17181a',bd:pop?'#111214':'#e8e7e3',btnBg:pop?'oklch(0.58 0.19 35)':'#fff',btnFg:pop?'#fff':'#17181a',btnBd:pop?'0':'1px solid #d6d4ce',cta:pl[1]===0?'Start Creating':'Choose '+pl[0],go:pl[1]===0?g.register:()=>{this.setState({coPlan:i-1,paid:false}); this.go('checkout');}};};
    const tplCatList=['All','TikTok','Instagram Reels','YouTube Shorts','YouTube','Product Ads','SaaS Ads','Real Estate','Ecommerce','Explainer','Education','Faceless Content'];
    const tplAll=this.TPL.map((t,i)=>{const d=this.tdim(t[3]); return {idx:i,name:t[0],cat:t[1],dur:t[2],ratio:t[3],c:this.F[(i*3)%10],fw:d[0],fh:d[1],open:()=>{this.setState({tpl:i}); this.go('template');}};});
    const tplItems=tplAll.filter(t=>(s.tcat==='All'||t.cat===s.tcat)&&(t.name+t.cat).toLowerCase().includes(s.tq.toLowerCase()));
    const T=this.TPL[s.tpl];
    const perVid={'Free providers':[0,0,0,0],'Mixed':[0.002,0.024,0.09,0.002],'Premium':[0.01,0.24,0.18,0.002]}[s.calcMode];
    const n=s.calcN, money=v=>'$'+(v).toFixed(2);
    const calcRows=[['Scripts',perVid[0]*n],['Images (6 per video)',perVid[1]*n],['Voiceover',perVid[2]*n],['Rendering on your server',perVid[3]*n]].map(r=>({k:r[0],v:money(r[1])}));
    const docsAll={
      install:{sec:'Getting started',title:'Installation',intro:'Upload the files to your server, point your domain at the public folder, and open the installer in your browser. The wizard handles the rest.',note:'Most installs take about five minutes. Shared hosting works if it supports PHP 8.2, FFmpeg and cron.',blocks:[{h:'1. Upload and set permissions',p:'Extract the package into your web root and make the storage folders writable.',code:'unzip reelsmith-2.4.1.zip -d /var/www/reelsmith\ncd /var/www/reelsmith\nchmod -R 775 storage bootstrap/cache'},{h:'2. Run the installer',p:'Visit https://your-domain.com/install and follow the steps: requirements, database, admin account, storage and AI providers.',code:''},{h:'3. Add the cron job',p:'Background workers generate and render videos. Add one line to your crontab.',code:'* * * * * cd /var/www/reelsmith && php artisan schedule:run >> /dev/null 2>&1'}]},
      providers:{sec:'Configuration',title:'Connecting AI providers',intro:'Reelsmith never ships with an AI provider built in. You connect your own accounts in Admin → AI Providers, and jobs route to the highest-priority healthy provider.',note:'Enable automatic fallback so jobs move to the next provider when one is rate limited.',blocks:[{h:'Free options to start',p:'OpenRouter free models for scripts, Cloudflare Workers AI or Hugging Face for images, and Edge TTS for voice. None of them need a card.',code:''},{h:'OpenAI-compatible endpoints',p:'Any API that speaks the OpenAI chat format works, including self-hosted vLLM or Ollama.',code:'Base URL:  http://10.0.0.12:8000/v1\nAPI key:   sk-local\nModel:     qwen2.5-32b-instruct'}]},
      whitelabel:{sec:'Configuration',title:'White-labeling',intro:'Change the app name, logo, favicon, colors, login page, emails and footer in Admin → White Label. Changes apply instantly across the app.',note:'Your license allows unlimited end users under your own brand.',blocks:[{h:'Custom domain',p:'Point your domain at the server and update APP_URL in your .env file.',code:'APP_NAME="Acme Video Cloud"\nAPP_URL=https://video.acme.co'}]},
      api:{sec:'Developers',title:'REST API',intro:'Create and render videos from your own apps. Authenticate with a key from Settings → API.',note:'Rate limits are set per plan in Admin → API.',blocks:[{h:'Create a video',p:'Returns immediately with a job ID. Poll the job or register a webhook.',code:'curl -X POST https://video.acme.co/api/v1/videos \\\n  -H "Authorization: Bearer rsk_live_..." \\\n  -d \'{"topic":"History of coffee","duration":60}\''}]}
    };
    const D=docsAll[s.doc];
    const docNav=[{t:'Getting started',items:[['install','Installation'],['req','Requirements'],['update','Updating']]},{t:'Configuration',items:[['providers','AI providers'],['whitelabel','White-labeling'],['plans','Plans & credits']]},{t:'Developers',items:[['api','REST API'],['hooks','Webhooks']]}].map(gp=>({t:gp.t,items:gp.items.map(d=>({label:d[1],bg:s.doc===d[0]?'#ebeae6':'transparent',fw:s.doc===d[0]?600:400,on:()=>this.setState({doc:docsAll[d[0]]?d[0]:'install'})}))}));
    const rpwMismatch=s.rpw2.length>0&&s.rpw!==s.rpw2;
    return {
      principles:[['server','Self-hosted by design','Your data and your customers\' data stay on infrastructure you control.'],['key-round','Your keys, your costs','We never resell AI. You pay providers directly, at their prices.'],['palette','Built to be rebranded','Every name, color and email can be yours. Customers never see ours.']].map(x=>({icon:'icon-'+x[0],t:x[1],d:x[2]})),
      legalNav:legalKeys.map(k=>({label:LEGAL[k][0],on:g[k],bg:s.legal===k?'#ebeae6':'transparent',fw:s.legal===k?600:400})), legal:{title:L[0],intro:L[1],sections:L[2].map(x=>({h:x[0],p:x[1]}))},
      relCols:isMobile?'minmax(0,1fr)':'160px minmax(0,1fr)',
      releases:[['v2.4.1','Sep 18, 2026','Stability fixes',[['Fixed','Groq rate-limit responses now trigger fallback correctly'],['Fixed','Captions no longer overlap the watermark on 1:1 videos'],['Improved','Installer detects NVENC hardware encoding']]],['v2.4.0','Sep 02, 2026','Video AI and a new editor timeline',[['New','Video AI providers: Fal.ai, Replicate, Runway and Luma'],['New','Four-track timeline with music ducking'],['New','Credit margin view in Admin → Credits'],['Improved','Scene regeneration keeps your edited narration']]],['v2.3.0','Jul 21, 2026','White-label emails',[['New','Email branding with live preview'],['New','Pages CMS with SEO fields'],['Improved','Faster first render on small VPS instances']]]].map(r=>({v:r[0],d:r[1],t:r[2],items:r[3].map(i=>({tag:i[0],t:i[1],bg:i[0]==='New'?'oklch(0.95 0.04 150)':i[0]==='Fixed'?'oklch(0.95 0.03 250)':'#f1f0ed',fg:i[0]==='New'?'oklch(0.42 0.12 150)':i[0]==='Fixed'?'oklch(0.45 0.13 250)':'#3a3c40'}))})),
      coCols:narrow?'minmax(0,1fr)':'minmax(0,1fr) 380px',
      coPlans:[['Starter',19,'1,500 credits · 30 videos'],['Professional',49,'5,000 credits · unlimited videos'],['Agency',99,'15,000 credits · 5 seats']].map((x,i)=>({name:x[0],d:x[2],price:'$'+(s.yearly?Math.round(x[1]*0.8):x[1])+'/mo',bd:s.coPlan===i?'#17181a':'#e1e0dc',dot:s.coPlan===i?'#17181a':'transparent',on:()=>this.setState({coPlan:i})})),
      payMethods:[['Card','credit-card'],['PayPal','wallet']].map(m=>({label:m[0],icon:'icon-'+m[1],bd:s.coMethod===m[0]?'#17181a':'#e1e0dc',on:()=>this.setState({coMethod:m[0],declined:false})})),
      co:{done:s.paid,form:!s.paid,card:s.coMethod==='Card',paypal:s.coMethod==='PayPal',declined:s.declined,cardBd:s.declined?'oklch(0.7 0.15 25)':'#e1e0dc',plan:coP[0],cycle:s.yearly?'yearly':'monthly',credits:coP[2].toLocaleString(),sub:'$'+coSub.toFixed(2),hasDisc:s.yearly,disc:'−$'+coDisc.toFixed(2),total:'$'+(coSub-coDisc).toFixed(2),payIcon:s.paying?'icon-loader-circle':'icon-lock',payAnim:s.paying?'rs-spin 1s linear infinite':'none',payLabel:s.paying?'Processing…':'Pay '+'$'+(coSub-coDisc).toFixed(2)},
      pay:()=>{ this.setState({paying:true}); setTimeout(()=>{ if(s.coMethod==='Card'&&!this.payTried){ this.payTried=true; this.setState({paying:false,declined:true}); } else this.setState({paying:false,paid:true,declined:false}); },1200); },
      sys:{...SY,hasMeta:!!SY.meta},
      obPad:isMobile?'20px 16px':'40px 24px', obCardPad:isMobile?'22px':'32px', obBars:[0,1,2].map(i=>i<=s.ob?'oklch(0.58 0.19 35)':'#e1e0dc'), ob:{s0:s.ob===0,s1:s.ob===1,s2:s.ob===2},
      obUses:useList.map(u=>{const on=s.obUses.includes(u[0]); return {t:u[0],icon:'icon-'+u[1],bd:on?'#17181a':'#e8e7e3',bg:on?'#f6f5f2':'#fff',on:()=>this.setState(x=>({obUses:on?x.obUses.filter(y=>y!==u[0]):[...x.obUses,u[0]]}))};}),
      obStack:[['Text','OpenRouter · free model','type','Ready','oklch(0.45 0.12 150)'],['Image','Cloudflare Workers AI','image','Ready','oklch(0.45 0.12 150)'],['Voice','Edge TTS','mic','Ready','oklch(0.45 0.12 150)'],['Video','Not connected','clapperboard','Unavailable','#8a8c91']].map(k=>({cat:k[0],name:k[1],icon:'icon-'+k[2],st:k[3],c:k[4]})),
      obIdeas:['Product launch teaser','3 tips for first-time buyers','Behind the scenes'],
      obBackOp:s.ob===0?0.4:1, obBack:()=>s.ob>0&&this.setState({ob:s.ob-1}), obNextLabel:s.ob===2?'Create video':'Continue',
      obNext:()=>{ if(s.ob<2) this.setState({ob:s.ob+1}); else window.location.href='/studio'; }, skipOb:()=>{ window.location.href='/studio'; },
      pwBars:[1,2,3,4].map(i=>i<=pwScore?pwCol:'#efeeea'), pwLabel:['Too short','Weak','Fair','Good','Strong'][pwScore],
      resetDone:s.resetDone, resetForm:!s.resetDone, doReset:()=>{ if(s.rpw===s.rpw2&&pwScore>=3) this.setState({resetDone:true}); },
      tfaBoxes:['3','1','7','','',''].map((v,i)=>({v,bd:i===3?'#17181a':'#e1e0dc'})),
      cookieOpen:!bare&&!s.cookie, cookieAccept:()=>{try{localStorage.setItem('rs_cookie','all')}catch(e){} this.setState({cookie:'all'});}, cookieEssential:()=>{try{localStorage.setItem('rs_cookie','essential')}catch(e){} this.setState({cookie:'essential'});}, goCookies:()=>{this.setState({legal:'cookies'}); this.go('legal');},
      showNav:!bare, isMobile:W<1060, notMobile:W>=1060, authLogo:narrow, nav, go:g, p, menuOpen:W<1060&&s.menu, menuIcon:s.menu?'icon-x':'icon-menu', toggleMenu:()=>this.setState({menu:!s.menu}),
      gut:isMobile?'18px':'28px', heroPad:isMobile?'56px 18px 36px':'96px 28px 56px', h1:isMobile?'42px':narrow?'58px':'76px', lead:isMobile?'17px':'19px', h2:isMobile?'34px':'48px', h3:isMobile?'26px':'34px',
      secPad:isMobile?'64px 18px':'112px 28px', secPadSm:isMobile?'40px 18px':'64px 28px', secB:isMobile?'64px':'112px', pagePad:isMobile?'40px 18px 72px':'72px 28px 112px',
      mockR:isMobile?'14px':'22px', mockPad:isMobile?'10px':'16px', mockCols:narrow?'minmax(0,1fr)':'220px minmax(0,1fr) 250px', mockSide:!narrow, mockRight:!narrow, mockH:isMobile?'340px':'440px', mockPrevH:isMobile?'300px':'400px', mockScenes,
      logos:[['OR','OpenRouter'],['GG','Google Gemini'],['GQ','Groq'],['CF','Cloudflare'],['HF','Hugging Face'],['FA','Fal.ai'],['EL','ElevenLabs'],['{ }','Custom API']].map(l=>({m:l[0],n:l[1]})),
      stageCols:W>=1100?'repeat(4,minmax(0,1fr))':W>=560?'repeat(2,minmax(0,1fr))':'minmax(0,1fr)',
      stages:[['CREATE','sparkles','Seven studios for video, cinematic, animation, ads, content, audio and automation.',['Video','Cinematic','Animation','Ads','Content','Audio']],['AUTOMATE','workflow','Drag-and-drop workflows, AI agents and schedules that run without you.',['Workflow builder','AI agents','Triggers','Schedules']],['PRODUCE','clapperboard','Multi-shot productions with consistent characters, styles and camera control.',['Scenes & shots','Characters','Visual styles','Repurposing']],['DEPLOY','rocket','REST API, webhooks and smart provider routing under your own brand.',['REST API','Webhooks','Smart routing','White label']]].map((x,i)=>({t:x[0],icon:'icon-'+x[1],d:x[2],items:x[3],bg:i===3?'#111214':'#fff',fg:i===3?'#fff':'#17181a',bd:i===3?'#111214':'#e8e7e3',chipBd:i===3?'#3a3c42':'#e1e0dc'})),
      pipeline:[['Idea','lightbulb','Topic, audience, platform'],['Script','type','Hook, body and CTA'],['Scenes','layout-list','Timed shots with prompts'],['Visuals','image','AI images, clips or uploads'],['Voice','mic','Neural or cloned voices'],['Captions','captions','Animated, on-brand'],['Render','film','MP4 via FFmpeg']].map((x,i)=>({n:String(i+1).padStart(2,'0'),t:x[0],icon:'icon-'+x[1],d:x[2],bg:i===6?'oklch(0.58 0.19 35)':'#f3f2ef',fg:i===6?'#fff':'#17181a'})),
      featCols:narrow?'minmax(0,1fr)':'minmax(0,1fr) minmax(0,1.1fr)', featPad:isMobile?'22px':'44px',
      features:[{eyebrow:'SCRIPT → SCENES',t:'The AI plans every shot. You stay in charge.',d:'A script becomes timed scenes with visual prompts, narration and captions. Drag to reorder, regenerate one scene, or rewrite a line.',pts:['Regenerate a single scene without starting over','Drag-and-drop scene order','Per-scene provider and model choice'],isScenes:true,isCost:false,isLabel:false},{eyebrow:'BRING YOUR OWN KEYS',t:'Your AI bill, not a subscription markup.',d:'Connect free providers to start, then add paid ones only where quality matters. You pay providers directly, at cost.',pts:['OpenRouter, Gemini, Groq, Cloudflare, Hugging Face','Any OpenAI-compatible endpoint','Automatic fallback when a provider is rate limited'],isScenes:false,isCost:true,isLabel:false},{eyebrow:'WHITE LABEL',t:'One install. Your brand on every screen.',d:'Rename the app, swap the logo and colors, and brand the login page and emails. Customers never see Reelsmith.',pts:['Live preview before publishing','Your own plans, prices and credits','Custom domain and email branding'],isScenes:false,isCost:false,isLabel:true}].map((f,i)=>({...f,textOrd:narrow?1:i%2?2:1,visOrd:narrow?2:i%2?1:2})),
      costRows:[['Script (≈150 words)','incl.','$0.00'],['6 AI images','incl.','$0.00'],['Neural voiceover','incl.','$0.00'],['1080p render','incl.','on your server']].map(c=>({k:c[0],a:c[1],b:c[2]})),
      brands:[['Acme Video','#2f6fed','#0f1b33'],['Clipwise','#e0541f','#231a14'],['Northwind Studio','#1f9d74','#0e2a22'],['Loop & Co','#8a4fe0','#1c1530']].map(b=>({n:b[0],pri:b[1],sec:b[2]})),
      ownerPts:[['server','Guided installer','Requirements check, database and AI setup in minutes.'],['palette','Full white-label','Name, logo, colors, login and emails.'],['layers','Plans & credits','Set your own prices and credit costs.'],['shield-check','Admin console','Users, providers, payments and logs.']].map(o=>({icon:'icon-'+o[0],t:o[1],d:o[2]})),
      reqs:[['PHP','8.2+'],['MySQL / MariaDB','8.0 / 10.6+'],['Extensions','pdo, gd, curl, zip'],['Storage','writable'],['FFmpeg','6.0+'],['Cron','every minute']].map(r=>({k:r[0],v:r[1]})),
      tplTeaser:tplAll.slice(0,isMobile?4:5),
      plansTeaser:[...plansBase.slice(0,3).map(planCard),{name:'Self-hosted license',price:'$89',per:'one-time',desc:'Install on your server, white-label, and sell your own plans.',pop:false,bg:'#fff',fg:'#17181a',bd:'#17181a',btnBg:'#17181a',btnFg:'#fff',btnBd:'0',cta:'Install & White-Label',go:g.docs}],
      faq:[['Do I need a paid AI subscription?','No. Connect free providers like OpenRouter free models, Cloudflare Workers AI and Edge TTS to create videos at no AI cost. Add paid providers later if you want higher quality or more capacity.'],['Where do my API keys live?','On your own server, encrypted at rest. Requests go straight from your installation to the provider. Nothing passes through us.'],['Can I resell it under my own brand?','Yes. The white-label settings change the name, logo, colors, login page, emails and footer. You set your own plans and credit prices.'],['What server do I need?','PHP 8.2+, MySQL or MariaDB, FFmpeg and cron. A small VPS works. The installer checks everything for you.'],['Is there a video editor?','Yes. It\'s a simple browser editor for scenes, text, captions, voice, music and transitions. It\'s built for business users, not video pros.']].map((q,i)=>({q:q[0],a:q[1],open:s.faq===i,icon:s.faq===i?'icon-minus':'icon-plus',on:()=>this.setState({faq:s.faq===i?-1:i})})),
      ctaPad:isMobile?'32px 24px':'52px 56px',
      fgCols:narrow?'minmax(0,1fr)':'260px minmax(0,1fr)',
      featGroups:[{t:'Create',d:'From a blank idea to a planned video.',items:[['lightbulb','From an idea','Type a topic; get a script and scene plan.'],['shopping-bag','From a product','Turn product details and photos into an ad.'],['link','From a URL','Repurpose a blog post or landing page.'],['layout-template','From a template','Start from a proven structure.']]},{t:'Produce',d:'Every asset, generated or uploaded.',items:[['image','AI visuals','Images or clips per scene, from your providers.'],['mic','Voiceover','Dozens of voices, or clone your own.'],['captions','Animated captions','Karaoke, pop and highlight styles.'],['music','Music','Mood-matched tracks with auto-ducking.']]},{t:'Edit',d:'A simple editor for business users.',items:[['film','Timeline editor','Scenes, voice, captions and music tracks.'],['replace','Replace media','Swap any scene visual in one click.'],['refresh-cw','Regenerate','Redo one scene without starting over.'],['palette','Brand kit','Logo, colors, fonts and watermark.']]},{t:'Run the business',d:'For owners of the installation.',items:[['users','User management','Plans, credits, suspensions, impersonation.'],['coins','Credits & plans','Your own pricing and usage rules.'],['code','REST API','Create videos from your own apps.'],['globe','White label','Your brand everywhere.']]}].map(fg=>({...fg,items:fg.items.map(x=>({icon:'icon-'+x[0],t:x[1],d:x[2]}))})),
      billing:this.chips(['Monthly','Yearly · save 20%'],s.yearly?'Yearly · save 20%':'Monthly',v=>this.setState({yearly:v!=='Monthly'})),
      plans:plansBase.map(planCard), planNames:plansBase.map(x=>x[0]),
      compare:[['Monthly credits',['50','1,500','5,000','15,000']],['Videos',['3','30','Unlimited','Unlimited']],['Max resolution',['720p','1080p','1080p','4K']],['Watermark',['Yes','—','—','—']],['Paid AI models',['—','✓','✓','✓']],['Custom voices',['—','—','✓','✓']],['API access',['—','—','✓','✓']],['Team seats',['1','1','2','5']],['White-label exports',['—','—','—','✓']]].map(r=>({k:r[0],v:r[1].map(t=>({t,c:t==='—'?'#b3b4b8':t==='✓'?'oklch(0.45 0.12 150)':'#17181a'}))})),
      byokSteps:[['01','Connect a provider','Paste an API key from OpenRouter, Gemini, Groq, Cloudflare, Hugging Face or any OpenAI-compatible API.'],['02','Pick models per step','Choose a model for scripts, images, video and voice. Mix free and paid.'],['03','Pay providers directly','Usage bills to your own provider accounts, at their prices. No markup.']].map(b=>({n:b[0],t:b[1],d:b[2]})),
      calc:{n,rows:calcRows,total:money(perVid.reduce((a,b)=>a+b,0)*n)}, setCalc:e=>this.setState({calcN:+e.target.value}), calcModes:this.chips(['Free providers','Mixed','Premium'],s.calcMode,v=>this.setState({calcMode:v})),
      provCats:[['Text AI','Scripts, hooks and prompts',[['OR','OpenRouter','Free models available',1],['GG','Google Gemini','Free tier',1],['GQ','Groq','Free tier',1],['CF','Cloudflare Workers AI','Free daily quota',1],['HF','Hugging Face','Free inference',1],['{ }','Custom OpenAI-compatible','Self-hosted or any API',0]]],['Image AI','Scene stills and thumbnails',[['CF','Cloudflare Workers AI','Free daily quota',1],['HF','Hugging Face','Free inference',1],['SA','Stability AI','Paid',0],['RP','Replicate','Pay as you go',0]]],['Video AI','Motion clips from prompts or stills',[['FA','Fal.ai','Pay as you go',0],['RP','Replicate','Pay as you go',0],['RW','Runway','Paid',0],['LM','Luma','Paid',0]]],['Voice AI','Narration and voiceover',[['ET','Edge TTS','Free, no key',1],['PI','Piper','Free, self-hosted',1],['EL','ElevenLabs','Paid, voice cloning',0],['OA','OpenAI TTS','Paid',0]]]].map(c=>({t:c[0],d:c[1],items:c[2].map(i=>({m:i[0],n:i[1],tier:i[2],c:i[3]?'oklch(0.45 0.12 150)':'#6b6d72'}))})),
      tq:s.tq, setTq:e=>this.setState({tq:e.target.value}), tplCats:this.chips(tplCatList,s.tcat,v=>this.setState({tcat:v})), tplItems, tplEmpty:tplItems.length===0, tplCount:this.TPL.length,
      td:{name:T[0],cat:T[1],dur:T[2],ratio:T[3],c:this.F[(s.tpl*3)%10],ar:T[3].replace(':','/'),pw:{'9:16':'280px','16:9':'100%','1:1':'380px','4:5':'340px'}[T[3]]},
      tdScenes:[['Hook','Pattern-interrupt question','0:03'],['Problem','Name the pain','0:06'],['Story','Show the product in use','0:10'],['Proof','One concrete benefit','0:06'],['Offer','CTA with your link','0:05']].map((x,i)=>({n:String(i+1).padStart(2,'0'),t:x[0]+' · '+x[1],d:x[2]})),
      docsCols:narrow?'minmax(0,1fr)':'240px minmax(0,1fr)', docsPad:isMobile?'32px 18px 72px':'56px 28px 112px', docsSticky:narrow?'static':'sticky', docNav, doc:{...D,blocks:D.blocks.map(b=>({...b,hasCode:!!b.code}))},
      channels:[['mail','Email','support@reelsmith.dev'],['book-open','Documentation','Install guides and API reference'],['message-circle','Community forum','Ask other developers and agencies']].map(c=>({icon:'icon-'+c[0],t:c[1],d:c[2]})),
      contactSent:s.sent, contactForm:!s.sent, sendIcon:s.sending?'icon-loader-circle':'icon-send', sendAnim:s.sending?'rs-spin 1s linear infinite':'none', sendLabel:s.sending?'Sending…':'Send message',
      sendContact:()=>{this.setState({sending:true}); setTimeout(()=>this.setState({sending:false,sent:true}),1000);},
      authCols:narrow?'minmax(0,1fr)':'minmax(0,1fr) minmax(0,1fr)', authSide:!narrow,
      loginErr:s.loginErr, loginBd:s.loginErr?'oklch(0.7 0.15 25)':'#e1e0dc', loginIcon:s.logging?'icon-loader-circle':'icon-log-in', loginAnim:s.logging?'rs-spin 1s linear infinite':'none', loginLabel:s.logging?'Logging in…':'Log in',
      doLogin:()=>{ if(!s.loginErr&&!this.triedLogin){ this.triedLogin=true; this.setState({logging:true}); setTimeout(()=>this.setState({logging:false,loginErr:true}),900); } else { this.setState({logging:true,loginErr:false}); setTimeout(()=>{ window.location.href='/studio'; },900);} },
      rpw:s.rpw, rpw2:s.rpw2, setRpw:e=>this.setState({rpw:e.target.value}), setRpw2:e=>this.setState({rpw2:e.target.value}), rpwMismatch, rpwBd:rpwMismatch?'oklch(0.7 0.15 25)':'#e1e0dc',
      doRegister:()=>{ if(!rpwMismatch) this.go('verify'); },
      a:{login:s.page==='login',register:s.page==='register',forgot:s.page==='forgot',verify:s.page==='verify',reset:s.page==='reset',twofa:s.page==='twofa'},
      forgotSent:s.forgotSent, doForgot:()=>this.setState({forgotSent:true}),
      codeBoxes:['4','8','2','9','',''].map((v,i)=>({v,bd:i===4?'#17181a':'#e1e0dc'})), doVerify:()=>{ s.page==='verify'?this.go('onboarding'):(window.location.href='/studio'); },
      footCols:isMobile?'1fr 1fr':'1.4fr repeat(4,1fr)',
      footer:[{t:'Product',items:[['Features','features'],['Templates','templates'],['Pricing','pricing'],['AI Providers','providers'],['Changelog','changelog']]},{t:'Developers',items:[['Documentation','docs'],['Installation','docs'],['REST API','docs'],['License','license']]},{t:'Company',items:[['About','about'],['Contact','contact'],['Log in','login'],['Register','register']]},{t:'Legal',items:[['Terms','terms'],['Privacy','privacy'],['Refunds','refund'],['Cookies','cookies']]}].map(f=>({t:f.t,items:f.items.map(i=>({label:i[0],go:g[i[1]]}))}))
    };
  }
}
